module.exports = [
  {
    icon: "💞",
    title: "Young Hearts (18-25)",
    tagline: "Meet. Vibe. Grow.",
    desc: "Swipe-based friendship & hobby matching for the youth who want to connect and grow.",
    gradient: "from-pink-400 via-fuchsia-500 to-purple-500",
    image: "https://img.freepik.com/free-photo/smiling-young-couple-valentines-day-holding-points-red-heart-stick-with-i-love-you-text-isolated-orange-background_141793-110500.jpg",
  },
  {
    icon: "🕺",
    title: "Chill Bros (30-50 Men)",
    tagline: "New circles, old-school vibes.",
    desc: "Reconnect, find travel or sports buddies, and chill with good company.",
    gradient: "from-blue-400 via-indigo-500 to-purple-600",
    image: "https://img.freepik.com/free-photo/male-friends-walking-with-beer_23-2148179951.jpg",
  },
  {
    icon: "💃",
    title: "Soul Sisters (30-60 Women)",
    tagline: "Laugh. Share. Shine again.",
    desc: "A safe, inspiring space for women to connect, heal, and rediscover joy.",
    gradient: "from-rose-400 via-pink-500 to-red-500",
    image: "https://img.freepik.com/free-photo/two-pretty-girls-summer-park_1157-19499.jpg",
  },
  {
    icon: "💔",
    title: "New Beginnings",
    tagline: "It’s never too late to love or live again.",
    desc: "Meet companions, join healing circles, and rebuild confidence together.",
    gradient: "from-orange-400 via-red-400 to-pink-500",
    image: "https://img.freepik.com/free-photo/smiley-woman-bridge_23-2148523917.jpg",
  },
  {
    icon: "👵👴",
    title: "Golden Bonds (60+)",
    tagline: "Friendship has no age limit.",
    desc: "Find laughter, friendship, and new beginnings — every moment matters.",
    gradient: "from-amber-400 via-yellow-500 to-orange-500",
    image: "https://img.freepik.com/free-photo/couple-drinking-coffee-taking-selfie_23-2148293902.jpg",
  },
  {
    icon: "💫",
    title: "Together Again",
    tagline: "Love better. Grow closer.",
    desc: "Reignite your spark with couple activities and shared adventures.",
    gradient: "from-teal-400 via-emerald-500 to-green-500",
    image: "https://img.freepik.com/free-photo/full-shot-smiley-people-with-delicious-food_23-2150168139.jpg",
  },
];
